apiVersion: v1
kind: Service
metadata:
  name: checkout-shoppinglist-api-service
spec:
  selector:
    app: checkout-shoppinglist-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
  type: NodePort
